var baseUrl = 'https://epos.uatpaypoint.services/POSWebServiceProxyV2/rest/POSService/';

var apiViewer = angular.module('apiViewer', ['ngRoute'])
    .config(function($routeProvider){
        $routeProvider.when('/generateReport',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'generateReportController'
            })
        .when('/getAllTenderTypes',
            {
                templateUrl:'templates/getTemplateSpec.html',
                controller:'getAllTenderTypesController'
            })
        .when('/getAllVatCodes',
            {
                templateUrl:'templates/getTemplateSpec.html',
                controller:'getAllVatCodesController'
            })
        .when('/getMetadata',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getMetadataController'
            })
        .when('/getProduct',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getProductController'
            })
        .when('/getProductByCategory',
            {
                templateUrl:'templates/getTemplateSpec.html',
                controller:'getProductByCategoryController'
            })
        .when('/getProductByEan',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getProductByEanController'
            })
        .when('/getProductCategories',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getProductCategoriesController'
            })
        .when('/getProductCategory',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getProductCategoryController'
            })
        .when('/getProductMaintenance',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getProductMaintenanceController'
            })
        .when('/getPromotion',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getPromotionController'
            })
        .when('/getPromotionMaintenance',
            {
                templateUrl:'templates/getTemplateSpec.html',
                controller:'getPromotionMaintenanceController'
            })
        .when('/getQuickSellButton',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getQuickSellButtonController'
            })
        .when('/getQuickSellPageSetup',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getQuickSellPageSetupController'
            })
        .when('/getTenderButton',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getTenderButtonController'
            })
        .when('/getTenderPageSetup',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getTenderPageSetupController'
            })
        .when('/getTenderType',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getTenderTypeController'
            })
        .when('/getTenderTypeMaintenance',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getTenderTypeMaintenanceController'
            })
        .when('/getTillSettings',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'getTillSettingsController'
            })
        .when('/searchProducts',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'searchProductsController'
            })
        .when('/searchPromotions',
            {
                templateUrl:'templates/getTemplateGen.html',
                controller:'searchPromotionsController'
            })
        .otherwise(
            {
                template:'<h1>Welcome to T3 Products and Promotions</h1>'
            });
    });

